### ISSUE TITLE
Names updates do not show in the app automatically

### ISSUE THREAD

**Issue by plinnegan** [plinnegan/program-dataset-connector#1]
If a mapping is setup and then a user changes the name of a data set, data element or program indicator, because the names are stored in the datastore, these updates are not reflected in the app.

Need to make sure on app load that the datastore is updated if the names have changed.

**Comment by salihuM** [comment]
I updated a program indicator (appending some text to the filter) and regenerated mapping; the program indicators generated were not 'taking up' the appendage

**Comment by plinnegan** [comment]
FIx implemented for data set, data element and program indicator names. CO filter names still to do.

**Comment by plinnegan** [comment]
Co name update fix also applied
