### ISSUE TITLE
Split metadata payload when it's too large

### ISSUE THREAD

**Issue by plinnegan** [plinnegan/program-dataset-connector#10]
Some users are having issues where the generated metadata exceeds the request entity limit and so the POST request is throwing a 413 exception (request entity too large). The app should catch this if it occurs and split the payload into smaller parts.

**Comment by kstankevitz** [comment]
We just started experiencing this issue ... now that CO mappings are stored separately for each mapping, its actually possible to do multiple mappings per DE/PI pair. This has worked for us to get around the issue.

**Comment by plinnegan** [comment]
Good to know @kstankevitz 👍

**Comment by plinnegan** [comment]
This has now been implemented in 2.5 for both fetch and post requests.
