### ISSUE TITLE
Regression: CO filters global

### ISSUE THREAD

**Issue by plinnegan** [plinnegan/program-dataset-connector#14]
Previously a feature change was made to allow CO filters to be stored locally against a mapping, so a CO could have multiple filter definitions across different mappings, however this feature seems to have regressed in later releases and needs to be fixed.

**Comment by salihuM** [comment]
@plinnegan When will this be fixed, we are working on CHISU (OVC) project and have candidates for different PI filters

**Comment by plinnegan** [comment]
@salihuM I think this issue crept back in when I was making the changes for the COC overrides, so it would be great to check those are still working as expected with the new version.
