### ISSUE TITLE
Display warning when delete fails

### ISSUE THREAD

**Issue by kstankevitz** [plinnegan/program-dataset-connector#15]
When updating an existing mapping, PDAC first deletes the old PIs/PI group. However, if a PI is referenced elsewhere in the system (a favorite for example), PDAC is unable to delete it. In this case, the loading icon just goes indefinitely and you must refresh to continue. It would be great to see an error message indicating that a PI may be referenced elsewhere that is preventing the delete.

**Comment by plinnegan** [comment]
Issue reproduced using event reports.
