### ISSUE TITLE
Automatically set generated PIs to no public access

### ISSUE THREAD

**Issue by kstankevitz** [plinnegan/program-dataset-connector#18]
Once some bugs around sharing settings are fixed, it would be useful to set the generated PIs to no public access to prevent them from loading in analytics apps.

However, this is not relevant until this bug is addressed: [https://dhis2.atlassian.net/browse/DHIS2-15069](https://urldefense.com/v3/__https:/dhis2.atlassian.net/browse/DHIS2-15069__;!!ELf_LxN3sEQ!dMGDHaY2_xGGGezpOzQuoBFZQXpvklBE8qWNM-E27f4dS0nr08_Nl7sfd_li8fm9OtZQcFPMzf1xsITLz6Uo4cnsAC0$)

**Comment by plinnegan** [comment]
Thanks and noted!

**Comment by plinnegan** [comment]
For backwards compatibility and to cover all possible use cases, we have set the default to be public view and made this configurable via the data store.
