### ISSUE TITLE
DHIS2 server performance 

### ISSUE THREAD

**Issue by samuelanthonio** [plinnegan/program-dataset-connector#19]
It would be nice to reduce the number of program indicator API calls made with paging set to false. Every click of the "Generate Mapping" button was followed by a pull of PIs. 
API call looks something like this  
/api/37/programIndicators?filter=name%3Alike%3ArowId-&fields=id%2Cname%2CshortName%2Cexpression%2Cfilter%2Ccode%2Cdescription%2CaggregateExportCategoryOptionCombo%2CaggregateExportAttributeOptionCombo%2CattributeValues&paging=false

**Comment by plinnegan** [comment]
Hey Samuel, agreed swapping to paginated requests would be an improvement.

**Comment by plinnegan** [comment]
During the next round of updates I will add this to the list of tasks to work on, thanks for highlighting!

**Comment by plinnegan** [comment]
As of 2.5.0 app program indicator related requests (and indicator if required) are now paginated; this includes creation, updates and deletes.
