### ISSUE TITLE
Program indicators not absorbing update to base program indicator

### ISSUE THREAD

**Issue by salihuM** [plinnegan/program-dataset-connector#2]
I updated a program indicator (appending some text to the filter) and regenerated mapping; the program indicators generated were not 'taking up' the appendage

**Comment by plinnegan** [comment]
Hi @salihuM, make sure you clicked the update button next to the filter text, if you get a tick then and there is still an issue, then go to the datastore manager and check if the filter is updated there. If it is not then let me know and I can have a further look.

**Comment by plinnegan** [comment]
@salihuM Apologies I think I misunderstood your issue, it's changes to the base PI that are not being picked up? If clearing cache does not solve the issue, please run the reload apps maintenance task, if the original PI is still being used after this let me know. If you can reproduce on play that would help as well 👍

**Comment by plinnegan** [comment]
@salihuM I have tried to replicate this locally, but I am seeing the base PI updates applied to the generated PIs when I regenerate them, so I think this must have been a caching issue, therefore I'm closing this.
