### ISSUE TITLE
feat: Generate dataset for a period

### ISSUE THREAD

**Issue by delcroip** [plinnegan/program-dataset-connector#5]
Thanks for your work, as you mentioned in your video auto run (export-import) could be great when you have hundreds of orgUnit.

For me the ideal solution will be to be able to create a scheduler for a given dataset, then the scheduler will import-export for all OrgUnit of that given dataset, 
:
the scheduler will have only 1 parameters in addition to the dataset: lag in days --> day between the reference date (used to figure the period to generate) and the scheduler run date

br

**Comment by plinnegan** [comment]
Hi Patrick, thanks for this issue submission. For importing and exporting with lots of org units, you can create an org unit group which includes all of the org units you want, then export and import the data in one go.

Unfortunately a web app like the PDAC app does not have access to create scheduled tasks, so this is out of scope for the app at the moment.
